### ISSUE TITLE
Missing link in documentation.

### ISSUE THREAD

**Issue by DariaVazhenina** [blue-oil/blueoil#1136]
In the blueoil documentation there's a link with the following text: [the data augmentor reference page](https://docs.blue-oil.org/reference/data_augmentor.html), which gives `page not found` error. It's on [this](https://docs.blue-oil.org/usage/init.html) page.

**Comment by oatawa1** [comment]
Sorry to reply late.
Thank you for your finding.

The information can be found on this page.
https://docs.blue-oil.org/autoapi/blueoil/data_augmentor/index.html

I'm going to update the link.
