### ISSUE TITLE
Docs: Linux system image is out of date

### ISSUE THREAD

**Issue by Suikaba** [blue-oil/blueoil#1169]
The Linux system image referred in prerequisites is out of date.

The latest version is 18.04 , but the referred image is 16.04.

Setup an FPGA Board -- Download Linux system image (On your PC)
https://github.com/blue-oil/blueoil/blob/d9aa554d40f4ddc63a41f8b1c31f81bc1e4cd322/docs/install/install.md

**Comment by iizukak** [comment]
@Suikaba Thanks. We will deploy new OS image soon.
