### ISSUE TITLE
High CPU and Memory use by DatasetIterator class

### ISSUE THREAD

**Issue by ananno** [blue-oil/blueoil#185]
During dataset creation,
1. 8 processes is used for multi process dataset prefetch
> This will cause issue with CPU having less than 8 core. If the machine doesn't have enough cpu core available system can be frozen for long time.
2. A prefetch queue of 200 is used. For dataset with large images this number of queue can increase the RAM use significantly.

**Comment by ruimashita** [comment]
@ananno 
Thanks.
I agree. process size and queue size should be able to custom. And default queue size should be smaller.
