### ISSUE TITLE
Tutorial for object detection

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#20]
We already have implementation of object detection, but tutorial for the object detectn is not yet provided.

**Comment by iizukak** [comment]
@tkng @ruimashita 
Which dataset shoud we use for the tutorial?  WIDER FACE?

**Comment by iizukak** [comment]
I talked with @ruimashita and decided to investigate the license of both OpenImages and WIDER FACE at first.

**Comment by iizukak** [comment]
Open Images V4 is under CC License.

> The annotations are licensed by Google Inc. under CC BY 4.0 license. The images are listed as having a CC BY 2.0 license.
https://storage.googleapis.com/openimages/web/factsfigures.html

I could not find WIDER FACE license.

**Comment by tkng** [comment]
Pascal VOC is the best for me, since it's the most widely used dataset for object detection. (Sorry, the dataset format it's not officially supported yet. We should make another issues about that.)

**Comment by iizukak** [comment]
Object Detection tutorial is already done. So I close this issue.
