### ISSUE TITLE
The Cityscapes dataset loader wanted

### ISSUE THREAD

**Issue by nlpng** [blue-oil/blueoil#208]
Supporting [Cityscapes dataset](https://www.cityscapes-dataset.com/) for semantic segmentation task. 

# Background
We would like to implement dataset-loader for the cityscapes dataset using the `DatasetIterator` class in Blueoil.
- More detail dataset overview can be found [here](https://www.cityscapes-dataset.com/dataset-overview/)
- Examples of current Implementation of blueoil's data-loader are [here](https://github.com/nlpng/blueoil/tree/feature/one_cycle_policy/lmnet/lmnet/datasets)

**Comment by tkng** [comment]
ok to close
