### ISSUE TITLE
Mismatched order of thresholds for the decreasing function 

### ISSUE THREAD

**Issue by nlpng** [blue-oil/blueoil#247]
When applying threshold, from the [source code](https://github.com/nlpng/blueoil/blob/refact/threshold_skipping_pass/dlk/python/dlk/templates/src/func/impl/apply_thresholds.cpp), we had following comparison for the decreasing function: 
```
if (flag == -1) { // decreasing function
        if (d > ts2)
          new_d = 0;
        else if (d > ts1)
          new_d = 1;
        else if (d > ts0)
          new_d = 2;
        else
          new_d = 3;
      } 
```
However, in the generated threshold values for the decreasing function, the order is mismatched with the comparison above, below is an example provided by @n-nez
```
{58,-76,-211, -1}
```
If we apply with some input like:

| Input   | expected output  |  actual output  | 
|---|---|---|
| 43 | 1  | 0 | 
| 73 | 0  | 0 | 
| 47 | 1  | 0 |  
| 46 | 1  | 0 |  
| 66 |  0 | 0 |  
| 56 |  1 |  0 |  
| 53 | 1  | 0 |  
| 62 |  0 | 0 |  
| 61 |  0 | 0 |

**Comment by iizukak** [comment]
This issue is solved in #888
