### ISSUE TITLE
usb_camera_demo.py doesn't work with python3

### ISSUE THREAD

**Issue by Joeper214** [blue-oil/blueoil#259]
Tried this on `v0.6.0`

When I tried to run usb_camera_demo in Jetson TX2 with python3 it raises an import error.

I think `from Queue import Queue` doesn't work with python3.

https://github.com/blue-oil/blueoil/blob/3215aa45164da782fe15eb78ebc6bd7ead927be7/output_template/python/lmnet/utils/demo.py#L22

May we try to use `from multiprocessing import Queue` that is compatible with both?

**Comment by ruimashita** [comment]
`from multiprocessing import Queue` is thread and process safe, `from Queue import Queue` is only thread safe.

Recommend to work:
```
try: 
    import queue
except ImportError:
    import Queue as queue
```
https://stackoverflow.com/questions/29687837/queue-importerror-in-python-3

**Comment by Joeper214** [comment]
@ruimashita Thanks! Is it okay if I create a PR to apply this change?
