### ISSUE TITLE
Make easier to test DLK on local DE10-Nano

### ISSUE THREAD

**Issue by hadusam** [blue-oil/blueoil#260]
Currently, we cannot run `make test-dlk` easily on our own DE10-Nano.
I think it is good for the developer if we can test DLK locally w/o creating PR and waiting for CI.
This will also make it easier to setup CI agents for DLK test with FPGA.

## ToDo
- [x] Enable to specify the host of FPGA for test
- [x] Enable to run DLK test with our [official prepared OS image](https://docs.blue-oil.org/install/install.html#download-linux-system-image-on-your-pc) without additional setting for test

**Comment by iizukak** [comment]
@hadusam This issue is can be closed already?

**Comment by hadusam** [comment]
@iizukak Yes👍 My PR #261 has merged, so this can be closed.
