### ISSUE TITLE
TFRecord Support (through TensorFlow Datset)

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#266]
Want to support TFRecord using [TensorFlow Datasets](https://www.tensorflow.org/datasets).

Current blueoil support local datasets only. 
So each user should have own dataset in local machine.
We want to use Google Cloud Storage and TFRecord to increase usability.

**Comment by tfujiwar** [comment]
Implemented in https://github.com/blue-oil/blueoil/pull/276 .
