### ISSUE TITLE
WIDER_FACE dataset includes some 0 size bounding boxes

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#27]
Though we don't make it public, we support WIDER_FACE dataset format class. However, WIDER_FACE  includes some weird annotations, the height or width of bonding box is 0.

We have some choices to fix the problem.

- just skip 0 size bounding box
- set minimum width/height for bounding box
- just skip the image if a bounding box has 0 width or 0 height.

I don't know which one is better, but the 2nd one looks better.

**Comment by lm-konda** [comment]
Can we fix it in this way? (and set values ​​appropriately)
```
                    x, y, w, h, blur, expression, illumination, invalid, occlusion, pose, _ = line.split(" ")
                    w = max(w, 1); h = max(h, 1); # add this line 178
                    temp = [int(x), int(y), int(w), int(h), 0]
                    bbox.append(temp)
```

**Comment by iizukak** [comment]
@lm-konda @tkng 
Size 0 annotations have any reason?
If annotations are meaningless,

I think it's ok to skip
```
x, y, w, h, blur, expression, illumination, invalid, occlusion, pose, _ = line.split(" ")
if w <= 0 or h <= 0:
    continue
```

or set some threshold

```
x, y, w, h, blur, expression, illumination, invalid, occlusion, pose, _ = line.split(" ")
if w <= threshold or h <= threshold:
    continue
```
https://github.com/blue-oil/blueoil/blob/master/lmnet/lmnet/datasets/widerface.py#L177

**Comment by tkng** [comment]
@iizukak
> Size 0 annotations have any meaning?

I checked some images, found that size 0 annotation don't have any meaning.

**Comment by tkng** [comment]
This is an example, this image doesn't have any annotation except `0 0 0 0`. I think it seems better to skip the image itself, in the case of WIDER_FACE dataset.

![0_parade_parade_0_452](https://user-images.githubusercontent.com/96674/48828543-5d986f00-edb3-11e8-8a09-090fccaf12a0.jpg)

**Comment by a-hanamoto** [comment]
@tkng https://github.com/blue-oil/blueoil/blob/master/blueoil/datasets/widerface.py#L108
Now it seems that the script skips the image if a bounding box has 0 width or 0 height.
Can we close this issue?

**Comment by tkng** [comment]
@a-hanamoto Yes, we can.
