### ISSUE TITLE
Turning Inference speed in CPU part

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#274]
We want to speed up Inference speed.
Maybe s2d implementation can be more faster...

**Comment by primenumber** [comment]
Inference speed in CPU part is now much faster than previous in each architectures.
Is further optimization needed?

**Comment by tkng** [comment]
If further optimization is possible, we are very happy.

On the other hand, if you think further optimization is difficult or not worth trying, we can close this issue.

**Comment by iizukak** [comment]
I agreed.
Bye hard working of @primenumber , We have enough speed now I think.
