### ISSUE TITLE
Speeding up space to depth

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#287]
Current s2d implementation use only one thread.
We want to use multi thread.
If you have any idea to speed up, I want try.

**Comment by primenumber** [comment]
- define NDEBUG macto in order to disable TensorView assert (I tested, about 10% faster in first s2d)
- use NEON (easy to implement 64bit vectorization, hard to implement 128bit vectorization)
- unroll for ki/kj

**Comment by primenumber** [comment]
I optimized s2d.
- avoid to use TensorView::operator()
- thread parallelize
- SIMD parallelize

**Comment by iizukak** [comment]
Like #274, This issue can be closed now.
Thanks @primenumber for your effort.
