### ISSUE TITLE
Document how to measure inference speed.

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#319]
Blueoil developer often use `lm_*.elf` files to measure inference speed like
https://github.com/blue-oil/blueoil/pull/131#issuecomment-458037975

But there is no document in Usage Guide.
https://docs.blue-oil.org/usage/index.htm

Some of the contributors confusing how to get `npy` files and how to run.
I want to document how to measure inference speed.

**Comment by ed728** [comment]
There is currently no easy way as a user to turn time measurement on/off.
They seem to be enabled by default for lm_fpga in DLK Makefile, and on top of that the blueoil_convert.py script add the relevant CXXFLAGS to all the executable targets...
