### ISSUE TITLE
Improve performance of TensorView::operator()

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#322]
`TensorView` has little slower part.
We need to speeding up `TensorView::operator()` .

**Comment by primenumber** [comment]
It may comes from poor optimization by gcc for arm.

**Comment by primenumber** [comment]
Another reason is tensor sizes are not computed in compile time, so some optimizations cannot be applied.

**Comment by iizukak** [comment]
> It may comes from poor optimization by gcc for arm.

Oh, thank you for investigation🤕
