### ISSUE TITLE
Test for AArch64

### ISSUE THREAD

**Issue by primenumber** [blue-oil/blueoil#335]
There is no test for AArch64 now in dlk.

**Comment by primenumber** [comment]
- [ ] Prepare Raspberry Pi 3B/3B+/4B or Ultra96
- [ ] Add test for AArch64

**Comment by hadusam** [comment]
## Add test for AArch64
- [ ] Add code generation test to generate lib files for each test cases
- [ ] Add integration tests(binary execution) with buildkite-agent on Raspberry Pi

**Comment by hadusam** [comment]
### Add integration tests(binary execution) with buildkite-agent

- [ ] Change DLK test to output generated binary files into specified path
- [ ] Change buildkite pipeline job to gather binary outputs as artifacts
- [ ] Add new buildkite job with artifacts to test binary files on Raspberry Pi
