### ISSUE TITLE
There are some conflicts and unexpected commits on PR from a forked working branch

### ISSUE THREAD

**Issue by hadusam** [blue-oil/blueoil#349]
## Problem
I saw some conflicts and unexpected commits when trying to create PR from my forked working branch.
![スクリーンショット 2019-06-27 16 37 30](https://user-images.githubusercontent.com/12394960/60482988-947e1e00-9cce-11e9-9fb4-802debefc017.png)

**Comment by hadusam** [comment]
## How to solve it
Probably this occurred because the master branch was updated by directly.
I solved this by applying the changes in the master branch to my working branch as follows.
```sh
$ cd [my git repo dir]
$ git checkout [my working branch]
$ git remote add upstream https://github.com/blue-oil/blueoil.git
$ git rebase --onto upstream/master master [my working branch]
### Force push to origin's working branch
$ git push -f origin [my working branch]
```
After this, unexpected commits are removed.
![スクリーンショット 2019-06-27 16 40 09](https://user-images.githubusercontent.com/12394960/60483306-db204800-9ccf-11e9-8641-8af82377188b.png)

**Comment by iizukak** [comment]
@hadusam Oh, Thank you for sharing !!
