### ISSUE TITLE
Completely unused modules

### ISSUE THREAD

**Issue by ytfksw** [blue-oil/blueoil#361]
# Problems

Completely unused modules: **'pygame'**, **'psutil'**, **'setproctitle'** exist in dev.requirement.txt.
In particular, pygame has many dependent libraries, and it seems to be better removed from dev.requirement.txt.

**Comment by Joeper214** [comment]
@ytfksw Thanks for raising these issues. I'll address this.

**Comment by Joeper214** [comment]
@ytfksw In this case, `psutil` and `setproctitle` is used in parameter search feature implemented by @nlpng. So I can only remove `pygame` module.
