### ISSUE TITLE
Fix round

### ISSUE THREAD

**Issue by yd8534976** [blue-oil/blueoil#397]
- In `linear.py', 'linear_mid_tread_half_quantizer()` uses `quantized = tf.round(shifted * n) / n`.
- In `quantizer.h`, `func_QTZ_binary_channel_wise_mean_scaling` uses `tmp = roundf(tmp * n) / n`.

Where, `tf.round()` will round half to even. So `tf.round(2.5) = 2.0`. Yet `roundf(2.5) = 3.0`.

**Comment by primenumber** [comment]
We can use std::nearbyint/nearbyintf.
Behavior of these functions depends on rounding mode.
If current rounding mode is FE_TONEAREST, it is recommended to round half to even and glibc is so.
