### ISSUE TITLE
remove LmThingsOnATable class

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#433]
`LmThingsOnATable` class is currently used only from test files (test_yolo_v1.py, test_yolo_v2.py, etc.) To reduce maintenance cost, it would be better if we can remove this class.

**Comment by Joeper214** [comment]
If we remove this dataset class, does it mean we have to replace it with more used dataset class using object detection?

**Comment by iizukak** [comment]
@Joeper214 
Yes. 
It can be replaced with some dataset class. For example, `OpneImagesV4`
