### ISSUE TITLE
sort import order

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#448]
[In pep-8](https://www.python.org/dev/peps/pep-0008/#imports), import order is defined as follows:

> - Standard library imports.
> - Related third party imports.
> - Local application/library specific imports.
> You should put a blank line between each group of imports.

We should follow this style guide. 

[isort](https://github.com/timothycrosley/isort) looks a good tool to sort import order automatically.

**Comment by suttang** [comment]
@tkng Do you have remaining task in this issue?

**Comment by a-hanamoto** [comment]
@tkng It seems related PR has been merged so can we close this issue?

**Comment by tkng** [comment]
@a-hanamoto yes we can
