### ISSUE TITLE
add `global_step` variable as an argument for all loss function

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#458]
Currently, only object detection model receives the variable `global_step` as the third argument. Consequently, in `lmnet/executor/train.py`, we need an if statement to pass `global_step` only for object detection model.

IMO, conditional branching by task type should be avoided whenever possible. To this end, we can pass `global_step` for all network definitions.

**Comment by a-hanamoto** [comment]
`global_step` has been moved in https://github.com/blue-oil/blueoil/pull/999 so can we close this issue?

**Comment by tkng** [comment]
Yes, we can!
