### ISSUE TITLE
remove pandas dependency

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#484]
We're depending on `pandas`, but actually it's used for just reading CSV or json files.

To reduce disk image size, we should remove this dependency.

**Comment by suttang** [comment]
Currently, we are using pandas not only for reading CSV in the following codes.
we need to rewrite these codes.

https://github.com/blue-oil/blueoil/blob/502e844f76286ad10f4c21d3d9bfa2c36cac15ca/lmnet/lmnet/datasets/delta_mark.py#L272-L279

https://github.com/blue-oil/blueoil/blob/502e844f76286ad10f4c21d3d9bfa2c36cac15ca/lmnet/executor/output_event.py#L65-L89

Other pandas code is used for just reading CSV.

**Comment by lm-lily** [comment]
@iizukak 
Iizuka san, I created issue #1052 which is related to this issue. 
Do we still need delta mark in blueoil?

**Comment by lm-lily** [comment]
delta_mark.py with pandas dependency is ignored as filed in #1066 .
