### ISSUE TITLE
unify docstring style to Google style

### ISSUE THREAD

**Issue by tkng** [blue-oil/blueoil#498]
Currently, we're using two styles of docstring, Google Style and Numpy Style. We should choose one style.

My preference is Google Style, because I don't want to put a horizontal line `----------`.

I'd like to know the other member's opinions.

**Comment by yd8534976** [comment]
Google Style~

**Comment by Joeper214** [comment]
Google 👍

**Comment by tkng** [comment]
any other comments?

**Comment by ruimashita** [comment]
Google style
