### ISSUE TITLE
Refactor View.run() in view.py

### ISSUE THREAD

**Issue by yd8534976** [blue-oil/blueoil#503]
As @tsawada mentioned, View.run() is too long to read.

code structure is like
```
if self.op.op_type == "A":
    return "AAA"
elif self.op.op_type == "B":
    return "BBB"
...
```
A good solution is using a dict approach.

I think we can use an alternative `singledispatch` approach.
The code structure will be something like:
```
@singledispatch
def get_format_string(op):
    return "Op not supported!"


@get_format_string.register
def _(op: A):
    return "AAA"

@get_format_string.register
def _(op: B):
    return "BBB"

```

I think this approach should be clean to read. I'd like to hear your opinions.

**Comment by tsawada** [comment]
I like using plain simple function table than `@singledispatch`. It is easier to understand.

```
def op_A():
    do_something()

def op_B():
   do_different_things()

OP_TABLE = {
  ‘A’: op_A,
  ‘B’: op_B,
}

class View:
    def run(self, ...):
        op_func = OP_TABLE.get(op.op_type)
        if not op_func:
           raise NotImplementedError
        return op_func(args)
```

**Comment by tkng** [comment]
This is a duplicated issue of #478.

**Comment by tkng** [comment]
`View.run` method is only called in `network.tpl.cpp`.  Actual line is following:

```
{{ node.view.run() }}
```

We can just implement `view` method in each operator class implementation and remove `View` class itself.

**Comment by yd8534976** [comment]
@tkng You are right, I'll close this duplicated issue.
