### ISSUE TITLE
Move lmnet/*requirements.txt to top directory

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#534]
A lot of *requirements.txt exist in lmnet directory.
Should be moved to top directory of Blueoil repository.

`docker/Dockerfile` need to be changed.

**Comment by ed728** [comment]
@iizukak So all of the `$TOP/lmnet/*requirements.txt` file should be moved to `$TOP/lmnet/*requirements.txt` as I get it? There are quite a lot of them though...

**Comment by ed728** [comment]
@iizukak This seems fixed in `master`, so maybe close this?

**Comment by iizukak** [comment]
@ed728 Thanks. we can close now.
