### ISSUE TITLE
Wrong memoryLayout in func_QTZ_binary_channel_wise_mean_scaling

### ISSUE THREAD

**Issue by yd8534976** [blue-oil/blueoil#569]
NHWC is not a layout for kernel. It should be something like OHWC or HWCO.

But It seems `func_QTZ_binary_channel_wise_mean_scaling` may never be generated..

https://github.com/blue-oil/blueoil/blob/56f6e4451e1dc48b3206aab28dc7444d373b5994/dlk/python/dlk/templates/include/quantizer.h#L25

**Comment by primenumber** [comment]
`NHWC` or `HWNC` for kernel layout is widely used in dlk, it is better to rewrite.

**Comment by primenumber** [comment]
I think `func_QTZ_binary_channel_wise_mean_scaling` should be removed.
