### ISSUE TITLE
Rename QTZ_binary_channel_wise_mean_scaling and other quantizers

### ISSUE THREAD

**Issue by yd8534976** [blue-oil/blueoil#574]
All node.op in tensorflow graph uses camel case. But our customized `QTZ_binary_channel_wise_mean_scaling` and other quantizers use snake case. I think we'd better change them to keep consistency.
<img width="569" alt="Screen Shot 2019-10-30 at 11 26 57" src="https://user-images.githubusercontent.com/8168498/67823910-35a7a480-fb08-11e9-91f4-f4d5a28bd949.png">

**Comment by Joeper214** [comment]
Done in multiple PR's
