### ISSUE TITLE
Enable code editing without docker rebuild

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#64]
When I edit some python code in `lmnet` or `dlk`, docker image should be rebuild.
It's not comfortable.

I want to mount `lmnet` and `dlk` using `-v` when running docker.
https://github.com/blue-oil/blueoil/blob/master/blueoil.sh#L130-L137

**Comment by iizukak** [comment]
@tkng @ruimashita How do you think about this issue?

**Comment by ruimashita** [comment]
For development, It is so nice.
There are possibility someday we will provide docker image, so then,
I think, It is better to add option to `blueoil.sh` somethink like `-mount-volume` to enable mount `lmnet` and `dlk`.

**Comment by tkng** [comment]
I also think that this feature would be very nice.

Considering the possibility of "official docker image", I wonder if we can mount `lmnet` and `dlk` directory automatically. Does it sounds like a nice idea?

**Comment by iizukak** [comment]
I implemented tkng-san's way for the moment.
