### ISSUE TITLE
Rewrite blueoil test (by python ?)

### ISSUE THREAD

**Issue by ruimashita** [blue-oil/blueoil#66]
The current test of blueoil commands is written by pure bash. 
https://github.com/blue-oil/blueoil/blob/master/blueoil_test.sh

It makes difficult to write unit test of blueoil commands, I hope rewrite the test by another language with test framework.

**Comment by iizukak** [comment]
Test is now re-implemented by python.
https://github.com/blue-oil/blueoil/tree/master/tests
