### ISSUE TITLE
Fix or remove MaxPoolWithArgmax

### ISSUE THREAD

**Issue by primenumber** [blue-oil/blueoil#661]
MaxPoolWithArgmax operator is dead code now, and func_MaxPoolWithArgmax is broken now.
We should choose fix to be used or just remove MaxPoolWithArgmax.

**Comment by tkng** [comment]
I guess it's better to remove. As far as I know, this operator is no longer used.

The `Unpooling` operator assumes the existence of `MaxPoolWithARgmax` operator, hence we can remove the `Unpooling` operator at the same time.

**Comment by primenumber** [comment]
OK, I'll remove these operators.

**Comment by primenumber** [comment]
solved. https://github.com/blue-oil/blueoil/pull/662
