### ISSUE TITLE
Change default experiment_id in `blueoil/cmd/train.py`

### ISSUE THREAD

**Issue by yd8534976** [blue-oil/blueoil#673]
In `blueoil/cmd/train.py`. `experiment_id` will be `train_{TIMESTAMP}` by default.
https://github.com/blue-oil/blueoil/blob/2149f97862e9a0684f816cc27f16d461b8dcc3ad/blueoil/cmd/train.py#L71-L75

But in blueoil official [tutorials](https://docs.blue-oil.org/tutorial/image_det.html). `{Model name}_{TIMESTAMP}` will be given to users as below.
`$ tensorboard --logdir=saved/{Model name}_{TIMESTAMP} --port {Port}`

To clear up confusion, we could fix either tutorials or `train.py`. But I think `{Model name}_{TIMESTAMP}` as tutorials should be better here.

**Comment by iizukak** [comment]
model name from config.yml file name looks reasonable :)
