### ISSUE TITLE
Move code in lmnet directory to blueoil directory.

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#741]
`lmnet` directory name confuse user often.
It's means both network name and whole training system name.
We want to move things in `lmnet` to `blueoil`

- [x] `lmnet/configs` - > `blueoil/configs`
- [x] `lmnet/executor` - > `blueoil/cmd`
- [x] `lmnet/tests` -> `tests/`
- [x] `lmnet/lmnet` -> `blueoil/`
- [x] `lmnet/third_party` -> removed
- [x] `lmnet/tox.ini` -> removed
- [x] `lmnet/README.md` -> `docs/something.md` README shoud be edited. because it's contains deprecated sentence.

This is big issue!!
All of import code should be replace with new path.
We should done in several PRs.

In this issue, we will ignore sort order. After that we sort order again in #817

**Comment by iizukak** [comment]
@tfujiwar Issue created.

**Comment by iizukak** [comment]
I updated the directory structure.

Now I consider to move `lmnet/lmnet` to `lmnet/nn`, Because in `blueoil` directory, we have `cmd` and `converter` in the future. In this case, I think scripts in `lmnet/lmnet` is not same level as `cmd` and `converter`, it's good to add layer like `lmnet/lmnet`. Disucussed with @odoku and @suttang , I decide the new layer name as `nn`. The name comes from TensorFlow and PyTorch.

**Comment by tfujiwar** [comment]
Done.
