### ISSUE TITLE
Move and rename dlk to blueoil/converter

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#762]
We want to provide Blueoil as just one python package.
But, current Blueoil have `dlk` as independent python package.
Our main package directory is `blueoil`, So we need to move scripts in `dlk` to `blueoil`.

Here is the how move dlk.

- [x] `dlk/python/dlk/*` -> `blueoil/converter/*`
- [x] `dlk/python/tools` -> `blueoil/tools`
- [x] `dlk/utils` -> `blueoil/converter/utils`
- [x] `dlk/tests` -> `tests/unit/converter`
- [x] `dlk/.gitignore` -> `.gitignore` merge to root `.gitignore`
- [x] `dlk/.gitmodules` -> removed
- [x] `dlk/README.md` -> removed. Most of the text are deprecated
- [x] `dlk/setup.py` -> `setup.py` merge to root `setup.py`, include some requirements.
- [x] `dlk/setup.cfg` -> removed
- [x] `dlk/hw/intel/de10_nano` -> `hw/intel/de10_nano`
- [x] `dlk/docs` -> `docs/converter`
- [x] `dlk/examples` -> `blueoil/converter/examples`

We also need to change python import path.
This is big issue. We need to do in several PRs.

**Comment by iizukak** [comment]
@primenumber 
Is it ok to move dlk to blueoil directory?
I think it will conflict your project.

**Comment by primenumber** [comment]
@iizukak OK!

**Comment by iizukak** [comment]
We create `tests/unit` directory for unit tests.
This issue's structure is also changed.

**Comment by iizukak** [comment]
@kchygoe Thanks. We can close this issue.

**Comment by kchygoe** [comment]
👍
