### ISSUE TITLE
An Error for ipython

### ISSUE THREAD

**Issue by tk26eng** [blue-oil/blueoil#771]
An error has occured when I build the blueoil docker image with `make build`.
The message is:

```
ERROR: ipython 7.11.1 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
```

But maybe this error is not critical because docker image has been generated successfully after this error and it works well without any problems.

**Comment by iizukak** [comment]
@tk26eng Thanks. Can you update `prompt-toolkit` ?

**Comment by iizukak** [comment]
Solved.
