### ISSUE TITLE
Verify Keypoint Detection Tutorial Documentation

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#778]
- [x] Blueoil Installation
- [x] Traing Neural Network
- [x] Run inference on GPU server
- [x] Run inference on DE10-Nano (FPGA)

https://docs.blue-oil.org/tutorial/index.html
https://docs.blue-oil.org/tutorial/image_keypoint_detection.html
https://docs.blue-oil.org/tutorial/run_fpga.html

**Comment by oatawa1** [comment]
In the step 1.3.2 (https://docs.blue-oil.org/install/install.html#connect-to-the-fpga-board-on-your-pc), FPGA board do not response to the PC(keyboard) via serial connection under this command.
> sudo cu -l  /dev/[your_fpga_board]  -s 115200

The current environment
PC: MacBook Pro (16-inch, 2019) macOS Catalina version 10.15.3
FPGA: DE10-Nano (SoC FPGA) board


An alternative way to solve is to connect via screen instead.
>  screen /dev/[your_fpga_board] 115200

**Comment by iizukak** [comment]
@oatawa1 Thanks. Please write this problem as indipendent issue.

**Comment by oatawa1** [comment]
@iizukak Thanks. I create a new issue here.
[FPGA board do not response to the PC(keyboard) via serial connection #790](https://github.com/blue-oil/blueoil/issues/790)

**Comment by oatawa1** [comment]
After I follows the tutorial in 2.4.2 and use abouve example, the configuration file name is not be keypoint_detection_demo.yml. I think it should be my_config.yml. 

Thus, I created the pull request here [#797 ](https://github.com/blue-oil/blueoil/pull/797)

**Comment by oatawa1** [comment]
PR #827 solved this issue.

**Comment by iizukak** [comment]
@oatawa1 Thanks. We can close this issue.
