### ISSUE TITLE
Remove whaaaaat dependency

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#876]
`whaaaaat` is no more maintenanced.

https://github.com/markfink/whaaaaat

**Comment by kchygoe** [comment]
Now `prompt_toolkit==3.0.3` is not compatible with whaaaaat so that blue oil command doesn’t work correctly.

**Comment by iizukak** [comment]
@kchygoe Year, #882 is merged, then this problem will be fixed.
