### ISSUE TITLE
Missing Semantic Segmentation Interface

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#88]
Blueoil has Semantic Segmentation implementation but not available from `blueoil.sh`. We need to add Semantic Segmentation support for `blueoil.sh` and `blueoil` directory's scripts.

Here is the list of TODO

- [x] [PR1] Test dataset files.
  - [x] Data.
  - [x] Document.
- [x] [PR2] Implement dataset class.
  - [x] Introduce `CamvidBase` class.
  - [x] `Camvid` class inhert `CamvidBase` class.
  - [x] `CamvidCustom` class Imprementation.
  - [x] Unit Test for each classes.
- [x] [PR3] Interface for blueoil
  - [x] Config template file.
  - [x] `blueoil` directory python scripts.
  - [x] `blueoil_test.sh`
  - [x] Config files
  - [x] Fix `run.py` inference script
- [x] [PR6] Tutorial for Semantic Segmentation
  - [x] Documentation
  - [x] Manual test from other developer

**Comment by ruimashita** [comment]
@iizukak Yes, It is high priority. So many people ask us when the Sem Seg is supported.

**Comment by iizukak** [comment]
I made [PR](https://github.com/blue-oil/blueoil/pull/93) for this issue. 

But it is so Big. And I'll separete that PR for smaller PRs (maybe 4 or 5).

I wrote how to separate, here.
https://github.com/blue-oil/blueoil/issues/88#issue-396365721
