### ISSUE TITLE
Wrong order of comparing when flag is -1 

### ISSUE THREAD

**Issue by tk26eng** [blue-oil/blueoil#883]
https://github.com/blue-oil/blueoil/blob/4996bc43232fa8db9a965dc5365611a82d29cdcd/blueoil/converter/templates/src/func/impl/generic/apply_thresholds.cpp#L49-L57

When the above thresholds are applied to float data, the order of comparing is wrong.
The order should go from ts2 to ts0 and it should be inverted.

```
if (d > ts0) 
     new_d = 0; 
   else if (d > ts1) 
     new_d = 1; 
   else if (d > ts2) 
     new_d = 2; 
   else 
     new_d = 3;
```

We also need to re-check the NEON and AVX code.

**Comment by primenumber** [comment]
fixed by #888 .
