### ISSUE TITLE
yaml parser error when train network

### ISSUE THREAD

**Issue by lm-lily** [blue-oil/blueoil#897]
![Screenshot from 2020-03-05 19-40-10](https://user-images.githubusercontent.com/35982704/75973982-64e87b00-5f19-11ea-9482-0109df08c596.png)

I got yaml parser error when I tried to train network following Blueoil tutorial.
The error is as shown in the attached image.

**Comment by iizukak** [comment]
@lm-lily THanks.
yaml file looks broken.
This problem looks like this post.
https://stackoverflow.com/questions/24983938/what-does-yaml-parser-parsererror-expected-document-start-but-found-blo

Can you put your yaml file?

IMO, It's good to copy and paste error message, not screenshot.

**Comment by oatawa1** [comment]
@lm-lily Could you provide me more your `myconfig.yml`?

**Comment by lm-lily** [comment]
@oatawa1 
I am sorry I don't know how to judge the format.
Could you tell me how to judge it?
I tried to attach the file contents here but it appears as weird formatting, so I attach the screenshot of the code.
![Screenshot from 2020-03-06 16-19-25](https://user-images.githubusercontent.com/35982704/76061217-64f28480-5fc6-11ea-94b7-d5e4e5ded4ed.png)

**Comment by oatawa1** [comment]
@lm-lily Thank you for the file. This is a python format. (I could see it from `import` part)

I'm not quite sure how to clearly judge it, in thia case I classified it by the header of the file.

**Comment by oatawa1** [comment]
@lm-lily In case, you need to train it now, please manually change the configuration file extension to `.py`.

 Thank you for your point out. ^^ Now, I'm fixing the document.

**Comment by lm-lily** [comment]
@oatawa1 
Thank you very much for the solution!

**Comment by iizukak** [comment]
@lm-lily This issue can be closed?
