### ISSUE TITLE
Redundant lines are generated during user interaction in generating configuration file

### ISSUE THREAD

**Issue by lm-lily** [blue-oil/blueoil#898]
During user input for "[?] Please choose augmentors:", every click on any arrow button will generate a new duplicated line of "[?] Please choose augmentors:". 
![Screenshot from 2020-03-05 21-07-06](https://user-images.githubusercontent.com/35982704/75980605-2907e280-5f26-11ea-9356-49eadd9be812.png)

**Comment by iizukak** [comment]
@lm-lily Thanks. It's a bug.

**Comment by iizukak** [comment]
@oatawa1 
It's looks related with #876 
Can you check?

**Comment by oatawa1** [comment]
@lm-lily 
Thank you for reporting.
I think this is the problem of [`inquirer`](https://pypi.org/project/inquirer/) package. I hope they will fix it.

This happened when the line exceeds the window width.
Please extend the window width and try again.
