### ISSUE TITLE
inference: run.py time measurement include library load

### ISSUE THREAD

**Issue by kchygoe** [blue-oil/blueoil#929]
v0.21.0

`output_template/python/run.py` can measure the time elapsed but it looks that first trial includes another process. 

```
...
[2020-03-17T16:32:43Z] INFO:__main__:Avg(func _pre_process): 0.0664009785652 sec.
--
  | [2020-03-17T16:32:49Z] INFO:__main__:Function _run took 6.28886604309 seconds to complete
  | [2020-03-17T16:32:49Z] INFO:__main__:Function _run took 0.611276865005 seconds to complete
  | [2020-03-17T16:32:50Z] INFO:__main__:Function _run took 0.614270925522 seconds to complete
...
```

**Comment by iizukak** [comment]
@kchygoe Thank you for the report!!

**Comment by tk26eng** [comment]
@kchygoe 
Now I 'm testing PRs with `.so`.
Your original problem is about when `.pb` file is read ?

The stability of measurements is getting improved with above PRs and it might be enough for `.so`.
But I'm suspecting `.pb` file still has problem.

**Comment by kchygoe** [comment]
@tk26eng Thank you for working on this! You are right. Above data was by `.pb` file. (sorry, it should have been mentioned) I will check the details out

**Comment by atsu-kan** [comment]
Is this issue still open?

**Comment by tk26eng** [comment]
> Is this issue still open?

Oh, This is finished.
I close this.
