### ISSUE TITLE
Add dataset loader for FER2013

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#933]
FER2013 is the dataset for Face Expression Recognition.
7 class classification.

It's looks better for tutorial than CIFAR10.

https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data

**Comment by kalpitthakkar-lm** [comment]
@iizukak I can work on this. Seems like a good issue to get warmed up.
Assigning myself to this.

**Comment by kalpitthakkar-lm** [comment]
Ah, infact, FER2013 dataset images are not available anywhere. We need to find an alternative.

**Comment by iizukak** [comment]
@kalpitthakkar-lm FER2013 dataset can be download from kaggle.
https://www.kaggle.com/c/challenges-in-representation-learning-facial-expression-recognition-challenge/data

**Comment by kalpitthakkar-lm** [comment]
@iizukak Can you download it?
I am not able to access it even after login. It keeps showing an error in loading data.

**Comment by iizukak** [comment]
@kalpitthakkar-lm 
Last month, I did download dataset. But now, there is not download link...

**Comment by kalpitthakkar-lm** [comment]
@iizukak What should we do? Do you have any idea for alternative example?

How about this: http://vision.ucsd.edu/~iskwak/ExtYaleDatabase/ExtYaleB.html

**Comment by iizukak** [comment]
@kalpitthakkar-lm 
Can you try to download?
https://www.kaggle.com/shawon10/facial-expression-detection-cnn/data

**Comment by kalpitthakkar-lm** [comment]
@iizukak This does not have the images!

**Comment by iizukak** [comment]
@kalpitthakkar-lm CSV contains image data

**Comment by kalpitthakkar-lm** [comment]
@iizukak I got the dataset.

Okay, so how should I proceed?

**Comment by iizukak** [comment]
@kalpitthakkar-lm Yes. Dataset loader.
metrics and loss, ... are already exist.

**Comment by iizukak** [comment]
closed with #1172
