### ISSUE TITLE
Verify profile_model.py documentation

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#975]
https://docs.blue-oil.org/usage/profile_model.html?highlight=profile_model%20py

This documentation is unsure correct or not.
If the command is outdated, Please update.

- [x] Training network (any network is ok) for 10 epoch
- [x] Convert
- [x] Execute `profile_model.py` follow the documentation
- [x] Copy and paste the result to this issue.

**Comment by oatawa1** [comment]
I ran two example commands in the link and I put log file and Model's profile and JSON in gist.

No error so far.

```
$ python blueoil/cmd/profile_model.py -i test_pfmodel_20200413171112 --restore_path saved/test_pfmodel_20200413171112/checkpoints/save.ckpt-7812 --bit 2 -uql conv1 -uql conv7
```
https://gist.github.com/oatawa1/67c215f521c86de74d58d964cff35627

```
$ python blueoil/cmd/profile_model.py -c config/test_pfmodel.py --bit 1
```
https://gist.github.com/oatawa1/21ade3fe9f642ab4a5e94c9cfc4cbf0f
