### ISSUE TITLE
List up current network specification

### ISSUE THREAD

**Issue by iizukak** [blue-oil/blueoil#991]
We need the network specification list in the documentation

Target Network
- LmnetV1Quantize
- LMFYoloQuantize
- LmSegnetV1Quantize

Inference Target
- `lm_fpga.elf`
- `lm_arm.elf`

For each netork,
- Please train each network for just 10 epoch.
- Execute `profile_model.py`
- Convert the checkpoint
- And execute `lm_fpga.elf` and `lm_arm.elf`
- Put whole result of elf file.

## LmnetV1Quantize
- [x] `profile_model.py`
- [x] Inference Speed (FPGA)
- [x] Inference Speed (Arm)

## LMFYoloQuantize
- [x] `profile_model.py`
- [x] Inference Speed (FPGA)
- [x] Inference Speed (Arm)

## LmSegnetV1Quantize
- [x] `profile_model.py`
- [x] Inference Speed (FPGA)
- [x] Inference Speed (Arm)

**Comment by oatawa1** [comment]
## LmnetV1Quantize
- Inference Speed (FPGA)   **6.769** ms
- Inference Speed (Arm)    **16.526** ms
https://gist.github.com/oatawa1/ccd9f2d4879f7b2aace71a6448821242

## LMFYoloQuantize
- Inference Speed (FPGA) **59.011** ms
- Inference Speed (Arm) **141.915** ms
https://gist.github.com/oatawa1/2056a3b9242eff0853398b5c6bc8d51a

## LmSegnetV1Quantize
- Inference Speed (FPGA)      **394.196** ms
- Inference Speed (Arm)        **1431.74** ms
https://gist.github.com/oatawa1/90b899d43dfad2770baad42b12c309f7

## LmSegnetV1Quantize (Modify add preconvolution layer)
- Inference Speed (FPGA)        **400.509** ms
- Inference Speed (Arm)         **1437.04** ms
https://gist.github.com/oatawa1/78d261eded825315a9e46a086e961da8

**Comment by iizukak** [comment]
@oatawa1 Thanks. Can you create document?
